name: pyPATools
channels:
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - cycler=0.10.0
  - cython
  - fontconfig=2.13.1
  - freetype=2.10.1
  - git
  - h5py
  - icu=64.2
  - importlib-metadata
  - intel-openmp
  - jpeg
  - kiwisolver=1.2.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.37
  - libxml2=2.9.10
  - llvmlite=0.31.0
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mkl=2020.0
  - mkl-service=2.3.0
  - numba=0.48.0
  - numpy=1.18.1
  - occt=7.4.0
  - openssl=1.1.1f
  - pip
  - plotly
  - pyopencl=2019.1.2
  - pyopengl
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqtgraph
  - python
  - python-dateutil
  - python_abi
  - pythonocc-core=7.4.0
  - qt=5.12.5
  - scipy=1.4.1
  - setuptools
  - six=1.14.0
  - sqlite=3.30.1
  - tbb=2020.1
  - tornado=6.0.4
  - wheel=0.34.2
  - zlib=1.2.11
  - hdbscan
  - ffmpeg
  - meshio
  #- pip:
  #  - meshio
  #  - numpy-quaternion
  #  - pyqt5-sip
  #  - pyqtwebengine
  #  - qdarkstyle
  #  - git+https://github.com/DanielWinklehner/py_electrodes.git
  #  - git+https://github.com/DanielWinklehner/dans_pymodules.git
  #  - git+https://github.com/DanielWinklehner/PyPATools.git
  #  - git+https://github.com/bempp/bempp-cl.git
